import './initial/index'
import './slick-vertical/index'
import './carousel/index'
import './nav-bar/index'
import './project/index'
import './about/index'
import './service/index'
import './video/index'
import './news/index'
import './team/index'
import './partner/index'

